import { Link } from "react-router-dom";
import { APP_CONFIG } from "@/constants";

export default function HomePage() {
  return (
    <main className="page page-home">
      <section className="hero">
        <div className="hero-content">
          <p className="eyebrow">AI-Powered Deepfake Detection</p>
          <h1>Guard Your Digital Identity with FaceGuard</h1>
          <p className="hero-copy">
            In an era of advanced AI, distinguishing real from fake has never been more critical. FaceGuard offers
            cutting-edge analysis to detect sophisticated deepfakes, providing a safeguard for your digital presence.
            Upload an image and let our Vision Transformer model deliver a verdict with trusted accuracy.
          </p>
          <div className="hero-actions">
            <Link to="/upload" className="primary-btn">
              Launch Detector
            </Link>
            <Link to="/guide" className="secondary-btn">
              How It Works
            </Link>
          </div>
        </div>
        <div className="hero-card">
          <p className="result-label">Sample Analysis Result</p>
          <p className="result-main">FAKE</p>
          <p className="result-confidence">Confidence: 98.72%</p>
          <p className="result-note">Results are generated by a fine-tuned Vision Transformer model.</p>
        </div>
      </section>
    </main>
  );
}

